// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "@hotwired/turbo-rails"
import "controllers"
import "staple_food"
import "main_dish"
import "side_dish"
import "result"
import "staple_food_count"
import "main_dish_count"
import "side_dish_count"